spring:
  datasource:
    username: root
    password: glxswy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital2?characterEncoding=utf-8&serverTimezone=UTC
server:
  port: 3560
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qy.domain